import { useEditor, EditorContent } from "@tiptap/react";
import { FloatingMenu, BubbleMenu } from "@tiptap/react/menus";
import StarterKit from "@tiptap/starter-kit";
import Highlight from "@tiptap/extension-highlight";
import Snackbar from "@mui/material/Snackbar";

import "./AIPatentEditor.css";
import { useState } from "react";
import axiosClient from "../api/axiosClient";
import type { PatentInteractionResponse } from "../api/types";
import Loader from "./Loader";
import MenuItem from "./MenuItem";
import { menuConfig, type PatentInstruction, type SuggestionActionId } from "./menuConfig";

const AIPatentEditor = () => {
  const [userEditorInput, setUserEditorInput] = useState<string>("");
  const [userInstructionsInput, setUserInstructionsInput] =
    useState<string>("");
  const [userSelectedText, setUserSelectedText] = useState<string>("");
  const [outputTxt, setOutputTxt] = useState<string>("");
  const [oldText, setOldText] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);
  const [displayErrorSnackbar, setDisplayErrorSnackbar] =
    useState<boolean>(false);
  const [aiSuggestionRequested, setAiSuggestionRequested] =
    useState<boolean>(false);
  const [isTxtHighlighted, setisTxtHighlighted] = useState<boolean>(false);
  const [selectedTextCordinates, setSelectedTextCordinates] = useState<{
    from: number;
    to: number;
    length: number;
  }>({ from: 0, to: 0, length: 0 });

  const editor = useEditor({
    extensions: [StarterKit, Highlight.configure({ multicolor: true })],
    content: `A cooling apparatus for an electronic device is disclosed, the apparatus comprising a heat sink which is thermally coupled to a processing unit, wherein said heat sink is configured to dissipate heat generated by the processing unit during operation, and further comprising a fan that is arranged in proximity to the heat sink for the purpose of directing an airflow across the heat sink so as to facilitate the removal of thermal energy therefrom.`,
    onSelectionUpdate: (data) => {
      const { from, to, empty } = data.editor.state.selection;

      if (!empty) {
        const selectedText = data.editor.state.doc.textBetween(from, to, " ");
        setSelectedTextCordinates({
          from,
          to,
          length: data.editor.state.doc.content.size,
        });
        setUserSelectedText(selectedText);
        setisTxtHighlighted(true);
      }
    },
    onUpdate: ({ editor }) => {
      setUserEditorInput(editor.getHTML());
    },
  });

  function aiVersionAction(actionId: SuggestionActionId) {
    if (!editor) return;
    const { from, to } = selectedTextCordinates;
    const replacementText = actionId === "approve" ? outputTxt : oldText;
    editor
      .chain()
      .focus()
      .insertContentAt({ from, to }, replacementText)
      .setTextSelection({ from, to: from + replacementText.length })
      .unsetHighlight()
      .run();
    setisTxtHighlighted(false);
    setAiSuggestionRequested(false);
  }

  function handleClose() {
    setDisplayErrorSnackbar(!displayErrorSnackbar);
  }

  function replacePatentContent(revisedTxt: string) {
    setOutputTxt(revisedTxt);
    const oldText = editor.state.doc.textBetween(
      selectedTextCordinates.from,
      selectedTextCordinates.to,
    );
    setOldText(oldText);
    const newText = revisedTxt ?? "";
    editor
      .chain()
      .focus()
      .insertContentAt(
        {
          from: selectedTextCordinates.from,
          to: selectedTextCordinates.to,
        },
        {
          type: "text",
          text: newText,
          marks: [
            {
              type: "highlight",
              attrs: {
                color: "#90EE90",
              },
            },
          ],
        },
      )
      .run();
    setSelectedTextCordinates({
      ...selectedTextCordinates,
      to: selectedTextCordinates.from + newText.length,
    });
    setAiSuggestionRequested(true);
  }

  function generatePatient(instruction: PatentInstruction | "" = "") {
    if (!editor) return;
    setLoading(true);
    const patientPayload = {
      instruction,
      editorData: instruction ? userSelectedText : userEditorInput,
      ...(!instruction && { userInteraction: userInstructionsInput }),
    };
    axiosClient
      .post<PatentInteractionResponse>(
        "/ai-patent/patent-interaction-text",
        patientPayload,
      )
      .then(({ data }) => {
        if (instruction) {
          replacePatentContent(data.data);
        } else {
          editor.chain().insertContent(data.data).run();
          setUserInstructionsInput("");
        }
      })
      .catch((error) => {
        console.error("Patent generation failed", error);
        setDisplayErrorSnackbar(true);
      })
      .finally(() => {
        setLoading(false);
      });
  }

  return (
    <div className="patent-editor-page">
      <Loader isLoading={loading} />
      <div className="patent-editor-header">
        <h1>AI Patent Editor</h1>
        <p>
          Select any text to rewrite it, or describe a change below. The AI
          suggests edits inline, and you accept or reject each one.
        </p>
      </div>
      <div className="patent-editor-wrapper">
        <EditorContent editor={editor} className="patent-editor-content" />
        <FloatingMenu editor={editor} className="patent-editor-menu">
          {menuConfig.floating.map((item) => (
            <MenuItem
              key={item.id}
              item={item}
              editor={editor}
              onAiAction={generatePatient}
            />
          ))}
        </FloatingMenu>
        <BubbleMenu
          editor={editor}
          className="patent-editor-menu"
          shouldShow={() => {
            return isTxtHighlighted;
          }}
        >
          {!aiSuggestionRequested ? (
            <>
              {menuConfig.bubble.default.map((item) => (
                <MenuItem
                  key={item.id}
                  item={item}
                  editor={editor}
                  onAiAction={generatePatient}
                />
              ))}
            </>
          ) : (
            <>
              {menuConfig.bubble.suggestion.map((item) => (
                <MenuItem
                  key={item.id}
                  item={item}
                  editor={editor}
                  onAction={aiVersionAction}
                />
              ))}
            </>
          )}
        </BubbleMenu>
      </div>
      <div className="patent-ai-input-box">
        <input
          type="text"
          placeholder="Tell AI what else needs to be changed"
          value={userInstructionsInput}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setUserInstructionsInput(e.currentTarget.value)
          }
        />
        <button
          onClick={() => generatePatient()}
          disabled={!userInstructionsInput}
        >
          Generate
        </button>
      </div>
      <Snackbar
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
        open={displayErrorSnackbar}
        message="Patent generation failed"
        onClose={handleClose}
        autoHideDuration={1000}
      />
    </div>
  );
};
export default AIPatentEditor;
